### ISSUE TITLE
Creating a context menu not working.

### ISSUE THREAD

**Issue by sharaalt** [notunderctrl/djs-commander#10]
Whenever i try to create a context menu in djs-commander it ask's me to add a description to the context menu which isn't possible. Will there be support for context menu's with djs-commander anytime soon, and is there a fix to my problem?

**Comment by notunderctrl** [comment]
Hi,
Unfortunately DJS-Commander doesn't support context menu at the moment.
I am however working on adding this functionality on the next update.
For now you'd have to manually register the context menu commands, or use the `ready` event to register them on startup.

**Comment by sharaalt** [comment]
Alright thank you is there any ETA for it?

**Comment by notunderctrl** [comment]
Hopefully by next week!

**Comment by sharaalt** [comment]
Is it out yet 👀

**Comment by martin-dsrz** [comment]
I'm looking forward to that too

**Comment by notunderctrl** [comment]
I completely forgot about this issue, sorry.
I want to say that DJS-Commander will not be receiving updates as I've shifted my focus to a new command/event handling library called "CommandKit". It supports everything DJS-Commander does (except the logger), and more. Context menu commands are also available.

Check it out on:
- [npm](https://npmjs.com/package/commandkit)
- [GitHub](https://github.com/notunderctrl/commandkit)
- [Documentation (includes guide on migrating from DJS-Commander)](https://commandkit.underctrl.io)
