### ISSUE TITLE
How to handle a "messageReactionAdd" event using djs-commander?

### ISSUE THREAD

**Issue by snotifxtk** [notunderctrl/djs-commander#4]
How can i trigger the **messageReactionAdd** event?

do i need to code it like this?

```
module.exports = (messageReactionAdd, client, handler) => {
  console.log(`${client.user.tag} is online.`);
};
```

trying to have the code below formatted to your DJS-commander one like above.

```
client.on('messageReactionAdd', async (reaction, user) => {
  const { message, emoji } = reaction;
};
```

**Comment by itsashau** [comment]
Within the Events folder you will create a folder called messageReactionAdd.
Within that folder you can call your file whatever you like as it will be ran when the event is ran.
![Screenshot 2023-04-28 085254](https://user-images.githubusercontent.com/9835318/235007584-8d5852fd-4a18-4d73-be1d-7626f8b11234.png)
Events folder
 - Folder (Event type)
    - File for event.
