### ISSUE TITLE
Feature request: allow user to specify winston logger

### ISSUE THREAD

**Issue by Lenme-exe** [notunderctrl/djs-commander#5]
Allow the user to pass along their own configured winston logger to the CommandHandler in order to replace the console.log way of logging the changes in commands.

In my project I have quickly realized that my logging isn't consistent because I use winston to log everything on my side of the code. But when starting my bot after a change, the console.logs print in between my winston logs, creating an unpleasant sight.

It's a small change but would definitely improve quality of life for those who also use winston loggers.

**Comment by notunderctrl** [comment]
Added in [v0.0.46](https://github.com/notunderctrl/djs-commander/pull/6)

**Comment by NanduWasTaken** [comment]
Why no Address?
